export const CATEGORIES = [
  {
    id: 'basics',
    label: '基础知识',
    color: '#ffab00',
    sections: [
      { id: 'home',        label: '首页',   icon: '🏠' },
      { id: 'voltage',     label: '电压',   icon: '⚡' },
      { id: 'ac-dc',       label: '交直流', icon: '〰️' },
      { id: 'series-parallel', label: '串并联', icon: '🔗' },
      { id: 'ohms-law',    label: '欧姆定律', icon: '📐' },
      { id: 'kirchhoff',   label: '基尔霍夫', icon: '🔁' },
      { id: 'ground-neutral', label: '接地零线', icon: '🛡️' },
      { id: 'current',     label: '电流',   icon: '〜' },
      { id: 'resistance',  label: '电阻',   icon: 'Ω'  },
      { id: 'multimeter',  label: '万用表', icon: '📟' },
      { id: 'power',       label: '功率',   icon: '💡' },
      { id: 'capacitor',   label: '电容',   icon: '⚙️' },
      { id: 'inductor',    label: '电感',   icon: '🌀' },
      { id: 'diode',       label: '二极管', icon: '▷'  },
      { id: 'transistor',  label: '三极管', icon: '🔺' },
      { id: 'transformer', label: '变压器', icon: '🔄' },
      { id: 'schematic',   label: '读电路图', icon: '📐' },
    ],
  },
  {
    id: 'repair',
    label: '维修工坊',
    color: '#ff6b35',
    sections: [
      { id: 'mm-measure',  label: '万用表5式', icon: '📟' },
      { id: 'light-fix',   label: '灯不亮',   icon: '💡' },
      { id: 'outlet-fix',  label: '插座没电', icon: '🔌' },
      { id: 'breaker-fix', label: '跳闸排查', icon: '⚡' },
      { id: 'teardown',    label: '拆机十诫', icon: '🔧' },
    ],
  },
  {
    id: 'practice',
    label: '互动练习',
    color: '#7c4dff',
    sections: [
      { id: 'calc-hub',     label: '计算器',   icon: '🧮' },
      { id: 'fault-sim',    label: '故障模拟', icon: '🔍' },
      { id: 'quiz-hub',     label: '小测验',   icon: '📝' },
      { id: 'line-game',    label: '连线游戏', icon: '🎮' },
      { id: 'repair-quest', label: '维修闯关', icon: '🏆' },
    ],
  },
  {
    id: 'home-elec',
    label: '家用电路',
    color: '#00e676',
    sections: [
      { id: 'home-ckt',    label: '家用电路', icon: '🏠' },
      { id: 'wiring',      label: '导线接线', icon: '🔌' },
      { id: 'outlet',      label: '开关插座', icon: '🔧' },
      { id: 'break-panel', label: '配电箱',   icon: '🗂️' },
      { id: 'relay',       label: '继电器',   icon: '⚙️' },
      { id: 'aircon',      label: '空调线路', icon: '❄️' },
      { id: 'low-voltage', label: '弱电系统', icon: '📶' },
      { id: 'floor-heat',  label: '地暖浴霸', icon: '🌡️' },
      { id: 'safety',      label: '安全用电', icon: '🛡️' },
      { id: 'troubleshoot',label: '故障排查', icon: '🔍' },
      { id: 'meter-entry', label: '入户电表', icon: '⚡' },
      { id: 'ev-charger',  label: '充电桩',   icon: '🔌' },
      { id: 'solar',       label: '光伏',     icon: '☀️' },
      { id: 'lightning',   label: '防雷',     icon: '🌩️' },
      { id: 'smart-switch',label: '智能开关', icon: '📱' },
    ],
  },
  {
    id: 'appliance',
    label: '小电器',
    color: '#e040fb',
    sections: [
      { id: 'bldc-fan',        label: '无刷电机', icon: '🌀' },
      { id: 'flashlight',      label: '手电筒',   icon: '🔦' },
      { id: 'desk-lamp',       label: '台灯',     icon: '🪔' },
      { id: 'kettle',          label: '热水壶',   icon: '☕' },
      { id: 'hair-dryer',      label: '电吹风',   icon: '💨' },
      { id: 'power-bank',      label: '充电宝',   icon: '🔋' },
      { id: 'router',          label: 'WiFi路由', icon: '📡' },
      { id: 'rice-cooker',     label: '电饭锅',   icon: '🍚' },
      { id: 'washing-machine', label: '洗衣机',   icon: '🫧' },
      { id: 'bt-speaker',      label: '蓝牙音箱', icon: '🔊' },
      { id: 'wireless-charge', label: '无线充电', icon: '📳' },
      { id: 'e-toothbrush',    label: '电动牙刷', icon: '🪥' },
      { id: 'robot-vacuum',    label: '扫地机器人', icon: '🤖' },
      { id: 'microwave',       label: '微波炉',     icon: '📻' },
      { id: 'induction',       label: '电磁炉',     icon: '🍳' },
      { id: 'fridge',          label: '冰箱',       icon: '🧊' },
      { id: 'escooter',        label: '滑板车',     icon: '🛴' },
    ],
  },
  {
    id: 'energy',
    label: '新能源',
    color: '#00c853',
    sections: [
      { id: 'battery-tech',    label: '锂电池',   icon: '🔋' },
      { id: 'fast-charge',     label: '快充协议', icon: '⚡' },
      { id: 'ev-power',        label: '汽车三电', icon: '🚗' },
      { id: 'energy-storage',  label: '储能',     icon: '🏠' },
    ],
  },
  {
    id: 'advanced',
    label: '进阶动手',
    color: '#00e5ff',
    sections: [
      { id: 'soldering',    label: '焊接技术', icon: '🔩' },
      { id: 'oscilloscope', label: '示波器',   icon: '📊' },
      { id: 'breadboard',   label: '面包板',   icon: '🧩' },
      { id: 'pcb',          label: 'PCB设计',  icon: '🖥️' },
      { id: 'arduino',      label: 'Arduino',  icon: '⚡' },
    ],
  },
  {
    id: 'reference',
    label: '速查手册',
    color: '#607d8b',
    sections: [
      { id: 'wire-table',  label: '线径表',   icon: '📋' },
      { id: 'symbol-ref',  label: '符号',     icon: '📐' },
      { id: 'parts-ref',   label: '元件库',   icon: '🧰' },
    ],
  },
  {
    id: 'cosmos',
    label: '宇宙',
    color: '#9c7dff',
    sections: [
      { id: 'cosmos',        label: '宇宙知识', icon: '🌌' },
      { id: 'solar-system',  label: '3D太阳系', icon: '🪐' },
    ],
  },
];

export const ALL_SECS = CATEGORIES.flatMap(c => c.sections);
export const SEC_LABEL    = Object.fromEntries(ALL_SECS.map(s => [s.id, s.label]));
export const SEC_CATEGORY = {};
CATEGORIES.forEach(c => c.sections.forEach(s => { SEC_CATEGORY[s.id] = c; }));
